# Generated by Django 4.2.23 on 2025-06-27 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название профессии')),
                ('description', models.TextField(verbose_name='Описание профессии')),
                ('keywords', models.TextField(help_text='Введите ключевые слова через запятую', verbose_name='Ключевые слова для поиска')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
            },
        ),
        migrations.CreateModel(
            name='VacanciesByYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_general', models.BooleanField(default=False, verbose_name='Общая статистика')),
                ('content', models.TextField(verbose_name='HTML-содержимое таблицы')),
                ('chart_image', models.ImageField(upload_to='charts/', verbose_name='Изображение графика')),
                ('profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies_by_year', to='analyzer.profession')),
            ],
            options={
                'verbose_name': 'Статистика вакансий по годам',
                'verbose_name_plural': 'Статистика вакансий по годам',
            },
        ),
        migrations.CreateModel(
            name='VacanciesByCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_general', models.BooleanField(default=False, verbose_name='Общая статистика')),
                ('content', models.TextField(verbose_name='HTML-содержимое таблицы')),
                ('chart_image', models.ImageField(upload_to='charts/', verbose_name='Изображение графика')),
                ('profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies_by_city', to='analyzer.profession')),
            ],
            options={
                'verbose_name': 'Статистика доли вакансий по городам',
                'verbose_name_plural': 'Статистика доли вакансий по городам',
            },
        ),
        migrations.CreateModel(
            name='SkillsByYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_general', models.BooleanField(default=False, verbose_name='Общая статистика')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('content', models.TextField(verbose_name='HTML-содержимое таблицы')),
                ('chart_image', models.ImageField(upload_to='charts/', verbose_name='Изображение графика')),
                ('profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills_by_year', to='analyzer.profession')),
            ],
            options={
                'verbose_name': 'Статистика навыков по годам',
                'verbose_name_plural': 'Статистика навыков по годам',
            },
        ),
        migrations.CreateModel(
            name='SalaryByYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_general', models.BooleanField(default=False, verbose_name='Общая статистика')),
                ('content', models.TextField(verbose_name='HTML-содержимое таблицы')),
                ('chart_image', models.ImageField(upload_to='charts/', verbose_name='Изображение графика')),
                ('profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_by_year', to='analyzer.profession')),
            ],
            options={
                'verbose_name': 'Статистика зарплат по годам',
                'verbose_name_plural': 'Статистика зарплат по годам',
            },
        ),
        migrations.CreateModel(
            name='SalaryByCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_general', models.BooleanField(default=False, verbose_name='Общая статистика')),
                ('content', models.TextField(verbose_name='HTML-содержимое таблицы')),
                ('chart_image', models.ImageField(upload_to='charts/', verbose_name='Изображение графика')),
                ('profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_by_city', to='analyzer.profession')),
            ],
            options={
                'verbose_name': 'Статистика зарплат по городам',
                'verbose_name_plural': 'Статистика зарплат по городам',
            },
        ),
        migrations.CreateModel(
            name='ProfessionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profession_images/', verbose_name='Изображение')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='analyzer.profession')),
            ],
            options={
                'verbose_name': 'Изображение профессии',
                'verbose_name_plural': 'Изображения профессий',
            },
        ),
    ]
