# Generated by Django 4.2.23 on 2025-06-29 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_profession_last_updated_salarybycity_data_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarybyyear',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='skillsbyyear',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='vacanciesbycity',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='vacanciesbyyear',
            name='profession',
        ),
        migrations.DeleteModel(
            name='SalaryByCity',
        ),
        migrations.DeleteModel(
            name='SalaryByYear',
        ),
        migrations.DeleteModel(
            name='SkillsByYear',
        ),
        migrations.DeleteModel(
            name='VacanciesByCity',
        ),
        migrations.DeleteModel(
            name='VacanciesByYear',
        ),
    ]
