# Generated by Django 4.2.23 on 2025-06-29 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_remove_salarybyyear_profession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profession',
            name='last_updated',
        ),
        migrations.CreateModel(
            name='VacanciesByYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_general', models.BooleanField(default=False, verbose_name='Общая статистика')),
                ('content', models.TextField(verbose_name='HTML-содержимое таблицы')),
                ('chart_image', models.ImageField(upload_to='charts/', verbose_name='Изображение графика')),
                ('profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies_by_year', to='analyzer.profession')),
            ],
            options={
                'verbose_name': 'Статистика вакансий по годам',
                'verbose_name_plural': 'Статистика вакансий по годам',
            },
        ),
        migrations.CreateModel(
            name='VacanciesByCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_general', models.BooleanField(default=False, verbose_name='Общая статистика')),
                ('content', models.TextField(verbose_name='HTML-содержимое таблицы')),
                ('chart_image', models.ImageField(upload_to='charts/', verbose_name='Изображение графика')),
                ('profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies_by_city', to='analyzer.profession')),
            ],
            options={
                'verbose_name': 'Статистика доли вакансий по городам',
                'verbose_name_plural': 'Статистика доли вакансий по городам',
            },
        ),
        migrations.CreateModel(
            name='SkillsByYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_general', models.BooleanField(default=False, verbose_name='Общая статистика')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('content', models.TextField(verbose_name='HTML-содержимое таблицы')),
                ('chart_image', models.ImageField(upload_to='charts/', verbose_name='Изображение графика')),
                ('profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills_by_year', to='analyzer.profession')),
            ],
            options={
                'verbose_name': 'Статистика навыков по годам',
                'verbose_name_plural': 'Статистика навыков по годам',
            },
        ),
        migrations.CreateModel(
            name='SalaryByYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_general', models.BooleanField(default=False, verbose_name='Общая статистика')),
                ('content', models.TextField(verbose_name='HTML-содержимое таблицы')),
                ('chart_image', models.ImageField(upload_to='charts/', verbose_name='Изображение графика')),
                ('profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_by_year', to='analyzer.profession')),
            ],
            options={
                'verbose_name': 'Статистика зарплат по годам',
                'verbose_name_plural': 'Статистика зарплат по годам',
            },
        ),
        migrations.CreateModel(
            name='SalaryByCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_general', models.BooleanField(default=False, verbose_name='Общая статистика')),
                ('content', models.TextField(verbose_name='HTML-содержимое таблицы')),
                ('chart_image', models.ImageField(upload_to='charts/', verbose_name='Изображение графика')),
                ('profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_by_city', to='analyzer.profession')),
            ],
            options={
                'verbose_name': 'Статистика зарплат по городам',
                'verbose_name_plural': 'Статистика зарплат по городам',
            },
        ),
    ]
