# Generated by Django 4.2.23 on 2025-06-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_remove_profession_last_updated_vacanciesbyyear_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AddField(
            model_name='salarybycity',
            name='data_source',
            field=models.CharField(default='CSV', max_length=50, verbose_name='Источник данных'),
        ),
        migrations.AddField(
            model_name='salarybycity',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AddField(
            model_name='salarybyyear',
            name='data_source',
            field=models.CharField(default='CSV', max_length=50, verbose_name='Источник данных'),
        ),
        migrations.AddField(
            model_name='salarybyyear',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AddField(
            model_name='skillsbyyear',
            name='data_source',
            field=models.CharField(default='CSV', max_length=50, verbose_name='Источник данных'),
        ),
        migrations.AddField(
            model_name='skillsbyyear',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AddField(
            model_name='vacanciesbycity',
            name='data_source',
            field=models.CharField(default='CSV', max_length=50, verbose_name='Источник данных'),
        ),
        migrations.AddField(
            model_name='vacanciesbycity',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AddField(
            model_name='vacanciesbyyear',
            name='data_source',
            field=models.CharField(default='CSV', max_length=50, verbose_name='Источник данных'),
        ),
        migrations.AddField(
            model_name='vacanciesbyyear',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
    ]
